spring:
    # 数据库连接信息
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 085258
        url: jdbc:mysql://localhost:3306/tlias
    # 文件上传配置
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 100MB

# 阿里云OSS配置
aliyun:
    oss:
        bucketName: web-tlias-ppx
        endpoint: https://oss-cn-beijing.aliyuncs.com
        accessKeyId: LTAI5tCf7cQfsRv6uaNaXonk
        accessKeySecret: LmmH06TCN8GlxCUwlFaFRDbhpuya6J

# MyBatis配置
mybatis:
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
        map-underscore-to-camel-case: true


# Spring事务管理日志开关配置
logging:
    level:
        org.springframework.jdbc.support.JdbcTransactionManager: debug